variable "INSTANCE_TYPE" {}
variable "VPC_ID" {}
variable "PORT" {}
variable "PRIVATE_SUBNET_CIDR" {}
variable "SSH_PORT" {}
variable "WORKSTATION_IP" {}
variable "PRIVATE_SUBNET_ID" {}
variable "PROJECT" {}
variable "ENV" {}
